server.port=${PORT:8081}

# Database Configuration (PostgreSQL/H2/MySQL)
# For Render/Railway we'll use environment variables
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/TASK_DB?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}

# JPA / Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Google Client ID (Frontend and Backend synchronization)
google.client.id=1059711129517-7c9c9tevfj9d1l1p9913jh54ks72s57f.apps.googleusercontent.com

